### ISSUE TITLE
Site update plan 

### ISSUE THREAD

**Issue by KlonD90** [NilFoundation/nil.foundation#75]
1. [x] [Изменение типографики](https://github.com/NilFoundation/nil.foundation/issues/71)
2. [x] [Изменение отступов](https://github.com/NilFoundation/nil.foundation/issues/80)
3. [x] [Удаление анимации паттернов и обновление то как выглядит их состояние](https://github.com/NilFoundation/nil.foundation/issues/69)
4. [x] [Create WebButton component ](https://github.com/NilFoundation/nil.foundation/issues/70)
5. [x] [Создание компонента Card](https://github.com/NilFoundation/nil.foundation/issues/73)
6. [x] [Использование компонента WebButton на сайте](https://github.com/NilFoundation/nil.foundation/issues/72)
7. [x] [Использование компонента Card на сайте](https://github.com/NilFoundation/nil.foundation/issues/74)
8. [x] [Обновление компонента навигации](https://github.com/NilFoundation/nil.foundation/issues/76) Имеет меньший приоритет чем остальные задачи и может быть отложен после 6го ноября
9. [x] [Implement Toggle button component in ui-kit](https://github.com/NilFoundation/ui-kit/issues/171)  Имеет меньший приоритет чем остальные задачи и может быть отложен после 6го ноября
10. [x] [Обновление компонента футера](https://github.com/NilFoundation/nil.foundation/issues/78) Имеет меньший приоритет чем остальные задачи и может быть отложен после 6го ноября
11. [x] [Использование Toggle Button](https://github.com/NilFoundation/nil.foundation/issues/77) Имеет меньший приоритет чем остальные задачи и может быть отложен после 6го ноября
12. [x] [Изменение страницы Open positions](https://github.com/NilFoundation/nil.foundation/issues/85)
